#!/usr/bin/env bash

DATA=$(cat <&0)

if [ -d src/main/include ]; then
	for INCLUDE in $(ls -1 src/main/include); do
		what="{{include:$INCLUDE}}"
		with=$(cat "src/main/include/$INCLUDE")
		DATA="${DATA//$what/$with}"
	done
fi

echo "$DATA"