#!/usr/bin/env bash
set -eux

{{include:bash-lib}}
{{include:user-interaction}}

#fun: urlencode str1 str2 str3
urlencode() {
    old_lc_collate=${LC_COLLATE:-}
    LC_COLLATE=C
    local str="$@"
    local length="${#str}"
    for (( i = 0; i < length; i++ )); do
        local c="${str:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c" ;;
        esac
    done
    
    LC_COLLATE=$old_lc_collate
}

#fun: urldecode str1 str2 str3
urldecode() {
	local str="$@"
    local url_encoded="${str//+/ }"
    printf '%b' "${url_encoded//%/\\x}"
}

# env: default_answer
#      answer?
#      title?
#      question?
input-text() {
	if tty -s; then
		test -n "${title:-}" && echo "$title"
		local safe_default_answer=$(echo "${default_answer:-}" | head -1 | cut -c 1-50)
		if [[ -n "${safe_default_answer:-}" ]]; then
			read -e -p "${question:-input text} [${safe_default_answer}]:" answer
			if [[ -z "$answer" ]]; then
				answer="$safe_default_answer"
			fi
		else
			read -e -p "${question:-input text}:" answer
		fi
	else
		if installed yad; then
			answer=`yad --center --width 500 --entry --title "${title:-input text}" --text "${question:-text}" --entry-text="$default_answer"`
		elif installed zenity; then
			errcho 'warning: using zenity, consider installing yad, to prefill with clipboard'
			answer=`zenity --width 500 --entry --title "${title:-input text}" --text "${question:-text}" --entry-text="$default_answer"`
		else
			errcho 'neither yad nor zenity installed'
		fi
	fi
}


main() {
	local query="$@"

	if [[ -z "$query" ]]; then
		title='web search' question=query default_answer=$(read-clipboard) input-text
		query="$answer"
	fi

	if [ -n "$query" ]; then
		# local encoded_query=$(urlencode "$query")
		# see solutions on https://superuser.com/questions/1496083/google-feeling-lucky-url-causing-redirect-notice
		xdg-open 'https://www.google.com/search?btnI=1&q='"$query"
		#xdg-open "https://duckduckgo.com/?q=!+$query"
	else
		echo empty query
	fi

}

{{include:entry-point}}