#!/usr/bin/env bash

set -eu

main() {
		
	if [ -n "${CASE_DIR:-}" ]; then
		KASE_DIR="$CASE_DIR"
	fi

	if [ -z "${KASE_DIR:-}" ]; then
		KASE_DIR="$HOME/case"
	fi

	# if [ -z "${EDITOR:-}" ]; then
		
	# fi


	local title="$@"
	if [ -z "$title" ]; then
		if tty -s; then
			echo 'kase title'
			read title
		else
			# exit script if cancel
			title=`zenity --entry --text 'kase title' --title kase`
		fi		
	fi

	if [ -n "$title" ]; then
		mkdir -p "$KASE_DIR/$title"
		touch "$KASE_DIR/$title/notes.txt"
		subl --new-window --add "$KASE_DIR/$title" "$KASE_DIR/$title/notes.txt"
	else
		echo empty title
	fi

}

main "$@"
