#!/usr/bin/env bash

{{include:bash-lib}}
{{include:user-interaction.sh}}
{{include:file-editor.sh}}
{{include:external-tool.sh}}

# env: script_dir
main() {
	local note_title="$@"
	if [ -z "$note_title" ]; then
		question='case title' title='new case creation' default="$(read-clipboard)" user-input-read note_title

		if [[ -z "$note_title" ]]; then
			user-message 'empty title!'
			return 1
		fi
	fi

	local case_home_dir="$(get-case-home-dir)"
	local today=`date +%Y-%m-%d`
	local case_dir="$case_home_dir/${today}_$note_title"
	mkdir -p "$case_dir"
	safe-link "$case_dir" "$case_home_dir/latest"
	code --new-window --goto "$case_dir/notes.txt" "$case_dir"
}

# fun:
safe-link() {
	local target="$1"
	local link="$2"
	if [[ -e "$link" ]]; then
		if [[ -L "$link" ]]; then
			rm "$link"
		else
			local now=$(date '+%Y-%m-%d_%H-%M.%S')
			mv today "latest_backup_${now}"
		fi
	fi
	ln -s "$target" "$link"
}


# env: HOME
#      NOTE_DIR?
#      script_dir
get-case-home-dir() {
	if [[ -n "${NCASE_DIR:-}" ]]; then
		echo "$NCASE_DIR"
	elif [[ -d "$HOME/case" ]]; then
		echo "$HOME/case"
	else
		mkdir -p "$HOME/case"
		echo "$HOME/case"
	fi
}

# env: NOTE_EXT?
get-note-file-extension() {
	echo "${NOTE_EXT:-.txt}"
}


{{include:entry-point}}
