#!/usr/bin/env bash

{{include:bash-lib}}
{{include:user-interaction.sh}}
{{include:file-editor.sh}}
{{include:external-tool.sh}}

# env: script_dir
main() {
	local title="$@"
	if [ -z "$title" ]; then
		question='note title' title='new note creation' default="$(read-clipboard)" user-input-read title

		if [[ -z "$title" ]]; then
			message "empty title"
			return 1
		fi
	fi

	local today=`date +%Y-%m-%d`
	file-editor-run "$(get-notes-dir)/$today $title$(get-note-file-extension)"
}

read-clipboard() {
	if installed xclip; then
		xclip -out || true
	fi
}



# env: HOME
#      NNOTE_DIR?
#      script_dir
get-notes-dir() {
	if [[ -n "${NNOTE_DIR:-}" ]]; then
		echo "$NNOTE_DIR"
	elif [[ -d "$HOME/notes" ]]; then
		echo "$HOME/notes"
	elif [[ -d "$HOME/box/notes" ]]; then
		echo "$HOME/box/notes"
	else
		mkdir -p "$HOME/notes"
		echo "$HOME/notes"
	fi
}

# env: NOTE_EXT?
get-note-file-extension() {
	echo "${NOTE_EXT:-.txt}"
}

{{include:entry-point}}