#!/usr/bin/env bash
set -eu

{{include:bash-lib}}

# env: time
parse-exif-time() {
	local result="${time//:/-}"
	result="${result// /_}"
	echo -n "$result"
}

# env: file
#      tag
extract-exif() {
	exif --machine-readable --tag $tag $file 2> /dev/null | head -n 1
}


# env : file
file-ext() {
	local file_basename=$(basename -- "$file")
	local file_ext="${file_basename##*.}"
	if [[ -n "$file_ext" ]]; then
		echo -n ".$file_ext"
	fi
}

# env: file
extract-file-time() {
	local extracted_time
	# DateTimeOriginal (date/time when original image was taken)
	local extracted_time=$(tag=0x9003 extract-exif)
	if [[ -z "$extracted_time" ]]; then
		# CreateDate (called DateTimeDigitized by the EXIF spec.)
		extracted_time=$(tag=0x9004 extract-exif)
		if [[ -z "$extracted_time" ]]; then
			# ModifyDate (called DateTime by the EXIF spec.)
			extracted_time=$(tag=0x0132 extract-exif)
			if [[ -z "$extracted_time" ]]; then
				return 1
				# do not rename today
				extracted_time=$(date --reference "$file" +%Y-%m-%d_%H-%M-%S)
				if [[ -z "$extracted_time" ]]; then
					return 1	
				fi
			fi
		fi
	fi
	time="$extracted_time" parse-exif-time
}

# env: file
guess-file-time() {
	local candidate=$(extract-file-time)
	if [[ -n "$candidate" ]]; then
		return "$candidate"
	fi

	# sed -E 's/.*(20[0-9]{2})([0-9]{2})([0-9]{2})_([0-9]{2})([0-9]{2})([0-9]{2})(.*)/\1-\2-\3_\4-\5-\6/g'
}

# env: file
new-file-name() {
	local file_time=$(guess-file-time)
	if [[ -z "$file_time" ]]; then
		return
	fi
	local file_dirname=$(dirname "$file")
	local file_basename=$(basename "$file")
	local file_ext=$(file-ext | awk '{print tolower($0)}')
	echo -n "$file_dirname/$file_time${file_suffix:-}$file_ext"
}

# env: file
rename-file() {
	if [[ ! -f "$file" ]]; then
		errcho "$file not exists"
		return 1
	fi
	local file_new_name=$(new-file-name)

	if [[ "$file" == "$file_new_name" ]]; then
		errcho "$file already named, skip"
		return
	fi

	if [[ -z "$file_new_name" ]]; then
		errcho "$file does not contain info"
		return
	fi

	if [[ -e "$file_new_name" ]]; then
		local file_new_name_index=1
		while true; do
			file_new_name=$(file_suffix="_$(printf "%02d" $file_new_name_index)" new-file-name)
			if [[ -e "$file_new_name" ]]; then
				file_new_name_index=$[$file_new_name_index + 1 ]
			else
				break;
			fi
		done
		echo "cannot rename $file exact: already exist, rename to $file_new_name"
	fi

	mv "$file" "$file_new_name"
}

# env: file ...
rename-files() {
	if [[ -n "${1:-}" ]]; then
		while [[ -n "${1:-}" ]]; do
			file="$1" rename-file
			shift
		done
	fi
}


main() {
	file=$1 rename-files "$@"


}

main "$@"