#!/usr/bin/env bash

main() {
	local host="$1"
	print-host-pem-cert "$host" | crt-trust
}

print-host-pem-cert() {
	keytool -printcert -sslserver -rfc"$1" 
}

pem-to-crt() {
	openssl x509 -outform der -in - -out -
}

crt-trust() {
	ubuntu-crt-trust "$@"
}

# env: ?host
# env: RANDOM
ubuntu-crt-trust() {
	sudo dd of="/usr/local/share/ca-certificates/${host:-$RANDOM$RANDOM$RANDOM}.crt"
	sudo update-ca-certificates # -fresh
}


info() {
	openssl s_client -showcerts -servername gnupg.org -connect "$1" 2>/dev/null | openssl x509 -inform pem -noout -text
}


{{include:entry-point}}

